name = "fgo-farming-solver"
main = ".open-next/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "fgo-farming-solver"

[[kv_namespaces]]
binding = "CLOUD_SAVE"
id = "c621d47e509445a3a7f713702b3cb07e"

[[kv_namespaces]]
binding = "MASTER_DATA"
id = "306bbe537e9d4907809f82468df500e4"

[[d1_databases]]
binding = "DB"
database_name = "fgo-farming-solver-db"
database_id = "4bb0a615-9079-4233-b57f-a5725b9eb4da"

[vars]
NEXT_PUBLIC_SITE_URL = "https://fgo-farming-solver.faru.jp"

[observability]
enabled = true
