name = "fgo-data-updater"
main = "index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[triggers]
crons = ["*/30 * * * *"] # 30 分ごとに実行 (失敗時の MTTR 短縮)

[[kv_namespaces]]
binding = "MASTER_DATA"
id = "306bbe537e9d4907809f82468df500e4"

[observability]
enabled = true
